name: 'Platform.sh Cypress test suite'
description: 'Run Cypress test specs against platformSH site'
branding:
  icon: 'crosshair'
  color: 'green'

inputs:
  PLATFORMSH_KEY:
    description: "API key for connecting to Platform.sh"
    required: true
    type: string

  PLATFORMSH_ID:
    description: "ID for the Platform.sh project."
    required: true
    type: string

  ENVIRONMENT_NAME:
    description: "Which environment to check against - defaults to pr-NUMBER"
    default: "pr-${{ github.event.pull_request.number }}"
    required: false
    type: string

  WORKING_DIRECTORY:
    description: "The directory that contains package.json (default: ./)"
    default: "./"
    required: false
    type: string

  ALLOW_CANCEL_CRON:
    description: "Can we cancel on-going crons, to speed up deployment? default: 1"
    default: 1
    required: false
    type: integer

  FAILED_IMAGE_UPLOAD:
    description: "Should failing tests upload fail images to the Action artifacts?  default: 0"
    default: 0
    required: false
    type: integer

  FAILED_VIDEO_UPLOAD:
    description: "Should failing tests upload fail videos to the Action artifacts?  default: 0"
    default: 0
    required: false
    type: integer

  TARGET_CYPRESS_SPECS:
    description: "Specific Cypress specs to run. default: '*/**' (all available)"
    default: '*/**'
    required: false
    type: string

runs:
  using: "composite"
  steps:
    - uses: reload/action-platformsh-url@main
      id: platformsh_url
      with:
        PLATFORMSH_ID: ${{ inputs.PLATFORMSH_ID }}
        PLATFORMSH_KEY: ${{ inputs.PLATFORMSH_KEY }}
        ENVIRONMENT_NAME: ${{ inputs.ENVIRONMENT_NAME }}
        ALLOW_CANCEL_CRON: ${{ inputs.ALLOW_CANCEL_CRON }}

    - uses: actions/checkout@v3

    - name: Cypress tests
      uses: cypress-io/github-action@v5
      with:
        wait-on: ${{ steps.platformsh_url.outputs.url }}
        config: video=false
        working-directory: ${{ inputs.WORKING_DIRECTORY }}
        spec: ${{ inputs.TARGET_CYPRESS_SPECS }}
      env:
        CYPRESS_BASE_URL: ${{ steps.platformsh_url.outputs.url }}

    - uses: actions/upload-artifact@v3
      if: ${{ failure() && inputs.FAILED_IMAGE_UPLOAD == 1 }}
      with:
        name: cypress-screenshots
        path: ${{ inputs.WORKING_DIRECTORY }}/cypress/screenshots
        if-no-files-found: ignore

    - uses: actions/upload-artifact@v3
      if: ${{ failure() && inputs.FAILED_VIDEO_UPLOAD == 1 }}
      with:
        name: cypress-videos
        path: ${{ inputs.WORKING_DIRECTORY }}/cypress/videos
        if-no-files-found: ignore
